### ISSUE TITLE
Need to save the elfinder images on Amazon s3 any ideas!

### ISSUE THREAD

**Issue by akeelahmedqureshi** [phallstrom/el_finder#32]
I want to save the images/files on s3, uploaded using the el_finder. If you have any solution it would be really helpful.

Thanks in advance!

**Comment by phallstrom** [comment]
I don't.  Someone somewhere may have a fork that supports it, but I'm not aware of it.  Long ago I started to work on version 2 that would support this, but life/work got in the way and I haven't had a chance to revisit it.
