### ISSUE TITLE
Crop and Rotatate button not visible in image Resize dialog ?

### ISSUE THREAD

**Issue by coderubyonrails** [phallstrom/el_finder#39]
When I run elfinder-2.1.27 front-end with rails as backend, I can't see crop and rotate button in image resize elfinder dialog. When I run php version of elfinder the buttons are seen but when I use elfinder in rails app, same button are not seen. Elfinder version I'm using is 2.1.27 with elfinder gem.

**Comment by CodeLyokoXtEAM** [comment]
I think this conector isn't developed by them.
Main page says, 
> NOTICE
> 
> I no longer have the time to maintain this (haven't for a long time). If you have an interest in picking this up, let's talk and I can transfer the repository to you.

**Comment by phallstrom** [comment]
@coderubyonrails Pretty good chance that functionality doesn't exist in the rails app. I haven't touched this gem in a long long time (4 years?). Wish I had better news, but at this point if you want it, you'll need to add it yourself.  I'm open to transferring ownership of this gem as well if you want to run with it.
