### ISSUE TITLE
{"error":"Invalid command ''"}

### ISSUE THREAD

**Issue by sergey-pt** [phallstrom/el_finder#4]
Hello,

First of all, thanks for this gem, really appreciate.

But unfortunatly I have some trouble with installation, even when I'm using cloned example app.
I've got an error in browser when trying to get page with el_finder:

```
{"error":"Invalid command ''"}
```

My environment is Ubuntu 10.10, ruby-1.9.2-p290 via rvm, ImageMagick 6.6.2-6 , and a separate gemset for prevent any gem conflicts.

Would be really appreciate for any help.

**Comment by ZIedBargaoui** [comment]
Hi guys, I'm having the same problem, I followed literally the official example but still doesn't work.
